package com.example.models;
import java.util.Random;
import java.util.concurrent.BlockingQueue;
import java.time.Instant;

public class Producer implements Runnable {
    private BlockingQueue<Task> queue;
    private String producerName;
    private int numberOfTasks;
    private boolean highPriority;

    public Producer() {
    }

    public Producer(BlockingQueue<Task> queue, String producerName, int numberOfTasks, boolean highPriority) {
        this.queue = queue;
        this.producerName = producerName;
        this.numberOfTasks = numberOfTasks;
        this.highPriority = highPriority;
    }

    @Override
    public void run() {
        Random random = new Random();

        for (int i = 0; i < numberOfTasks; i++) {
            try {
                int priority = highPriority ? 1 : 5;
                Task task = new Task.Builder()
                        .name(producerName + "-Task-" + i)
                        .priority(priority)
                        .payload("Generated by " + producerName)
                        .createdTimestamp(Instant.now())
                        .build();

                queue.put(task);
                System.out.println(producerName + " submitted task: " + task);

                Thread.sleep(2000 + random.nextInt(2000));
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                System.err.println(producerName + " was interrupted");
            }
        }
    }

    public static class Builder {
        private BlockingQueue<Task> queue;
        private String producerName;
        private int numberOfTasks;
        private boolean highPriority;

        public Builder queue(BlockingQueue<Task> queue) {
            this.queue = queue;
            return this;
        }

        public Builder producerName(String producerName) {
            this.producerName = producerName;
            return this;
        }

        public Builder numberOfTasks(int numberOfTasks) {
            this.numberOfTasks = numberOfTasks;
            return this;
        }

        public Builder highPriority(boolean highPriority) {
            this.highPriority = highPriority;
            return this;
        }

        public Producer build() {
            Producer producer = new Producer();
            producer.queue = this.queue;
            producer.producerName = this.producerName;
            producer.numberOfTasks = this.numberOfTasks;
            producer.highPriority = this.highPriority;
            return producer;
        }
    }

    public static Builder builder() {
        return new Builder();
    }
}
