package com.example.producer;
import com.example.enums.TaskStatus;
import com.example.core.Task;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.BlockingQueue;
import java.time.Instant;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.PriorityBlockingQueue;
import java.util.concurrent.atomic.AtomicInteger;

public class Producer implements Runnable {
    public static Logger logger = LoggerFactory.getLogger(Producer.class);
    public static BlockingQueue<Task> queue = new PriorityBlockingQueue<>();
    public static ConcurrentHashMap<UUID, TaskStatus> taskStatusMap = new ConcurrentHashMap<>();
    private String producerName;
    private int numberOfTasks;
    private boolean highPriority;
    public static final AtomicInteger submittedCount = new AtomicInteger(0);

    public static int getSubmittedCount() {
        return submittedCount.get();
    }
    public Producer() {}

    public Producer(String producerName, int numberOfTasks, boolean highPriority) {
        this.producerName = producerName;
        this.numberOfTasks = numberOfTasks;
        this.highPriority = highPriority;
    }

    @Override
    public void run() {
        Random random = new Random();

        for (int i = 1; i <= numberOfTasks; i++) {
            try {
                int priority = highPriority ? 1 : 5;
                Task task = new Task.Builder()
                        .name(producerName + "-Task-" + i)
                        .priority(priority)
                        .payload("Generated by " + producerName)
                        .createdTimestamp(Instant.now())
                        .build();
                Thread.sleep(1000);
                taskStatusMap.put(task.getId(), TaskStatus.SUBMITTED);
                queue.put(task);
                submittedCount.incrementAndGet();

                logger.info("{} {} submitted task: {} {}", Thread.currentThread().getName(), producerName, i, task);
                logger.info("Current taskStatusMap after submission: {}", taskStatusMap);
                Thread.sleep(200 + random.nextInt(2000));
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                logger.warn("{} was interrupted", producerName);
            }
        }
    }

    public static class Builder {
        private String producerName;
        private int numberOfTasks;
        private boolean highPriority;


        public Builder producerName(String producerName) {
            this.producerName = producerName;
            return this;
        }

        public Builder numberOfTasks(int numberOfTasks) {
            this.numberOfTasks = numberOfTasks;
            return this;
        }

        public Builder highPriority(boolean highPriority) {
            this.highPriority = highPriority;
            return this;
        }

        public Producer build() {
            Producer producer = new Producer();
            producer.producerName = this.producerName;
            producer.numberOfTasks = this.numberOfTasks;
            producer.highPriority = this.highPriority;
            return producer;
        }
    }

    public static Builder builder() {
        return new Builder();
    }
}
